### ISSUE TITLE
ISO 3166 country code 

### ISSUE THREAD

**Issue by coulix** [peopledoc/workalendar#13]
http://www.ciolek.com/owtrad/iso3166-countrycodes.html

It would be nice to be able to be able to load a Calendar from its country code.
For now the API requires us to do

```
from workalendar.europe import FranceCalendar
```

But in an environment where I need to dynamically get the holidays dates based on a country code something like

```
from workalendar import ISO3166Calendar
calendar =  ISO3166Calendar.from_code("KR") ?
```

Just an idea.

**Comment by JanMalte** [comment]
This is related to #96, once it is done, a simple lookup function for country codes could be added.

**Comment by Natim** [comment]
I also think we should start this sooner than later.
It is up to the developer to make sure workcalendar can handle the calendar its application needs and add the missing ones. So if I want to use UK and French one, why not allow me to load them from the locale my user is using in their session?

**Comment by JanMalte** [comment]
@coulix Which calendar should be returned, if you for example the calendar for 'DE'?
There are nearly 16 different holiday calendars for Germany and not one general calendar.

**Comment by coulix** [comment]
Maybe a default one with the possibility of passing a subtype.

    calendar =  ISO3166Calendar.from_country_code("DE", type="foobar") ?

**Comment by rain01** [comment]
It would be very useful feature.

**Comment by thibault** [comment]
Hi everyone.

Small world… :)

I'm also interested by thing kind of feature, because I have the same use case. I've got users located in countries, and I need to check if today is a work day for every user. Thus, I need a mechanism to dynamicaly fetch calendars.

Now, I see that this issue is opened since 2013. Did anyone come up with something, or did I miss something? I couldn't find anything related to such a feature, though. Could you tell me if this issue was abandoned, or what is it's precise status?

Trying to be productive, here are my personal answers to some of the questions raised in this conversation.

> What happens if we don't have the right calendar? What would be the fallback then?

I think we can agree it's almost impossible to be 100% precise when deciding if a particular date is a work day or not, so, as a workalendar user, I think it's reasonable to expect that some calendars won't be available anyway. Just raising an exception or returning `None` is fine with me.

> Which calendar should be returned, if you for example the calendar for 'DE'?

Maybe return the country-wide default calendar, and add another lookup function to select calendar by name?

Anyway, thank you for this awesome life-saving lib.

**Comment by thibault** [comment]
For the record, here is a (highly inefficient) piece of code I came up with:

```python
import sys
import inspect
from pkgutil import iter_modules
from importlib import import_module


def get_workalendar_class(country):
    country_name = country.name
    for finder, name, ispkg in iter_modules(workalendar.__path__):
        module_name = 'workalendar.{}'.format(name)
        import_module(module_name)
        classes = inspect.getmembers(sys.modules[module_name], inspect.isclass)
        for class_name, _class in classes:
            if _class.__doc__ == country_name:
                return _class()

    return None
```

**Comment by Natim** [comment]
We could have calendar to register themselves to a global dict instead.

**Comment by thibault** [comment]
@Natim That would be the easiest and most convenient method indeed.

**Comment by brunobord** [comment]
> We could have calendar to register themselves to a global dict instead.

This dictionary could be structured to handle the "more than one calendar for a given country". That way, one could fetch the "national / federal" calendar for general use, and get more fine-grained information if providing the right province/state.

**Comment by brunobord** [comment]
what I'm trying to say is that we could define a spec first.

* if no calendar is known with the provided code, return None,
* if one calendar exists for this country code, return it. via a tuple? ``(CalendarClass, {})``
* if more thatn one calendar exists for this country code, return the default one, along with the regional calendars: ``(DefaultCalendarClass, {'region1', Region1CalendarClass, 'region2': Region2CalendarClass})``

what do you think?

**Comment by Natim** [comment]
Seems good :)

**Comment by nandoflorestan** [comment]
Nope. Too many return options. While Bruno's specification would work for anybody, I believe it's easier for the user if we always return a dict:

- {}
- {"\__default__": DefaultCalendar}
- {"\__default__": DefaultCalendar, "São Paulo": SaoPauloCalendar}

**Comment by thibault** [comment]
I feel @brunobord's solution is slightly more pythonesque, but that's just my opininion. A dict would work too.

However, I think one should not forget the initial need expressed in this issue, which is being able to dynamically lookup a calendar based on runtime available data.

Such a lookup would be made easier if each calendar was indexed by a normalized key. I think the [Iso 3166-1 alpha 3 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) would be a good candidate, because is commonly available and is easy to read.

Here is an embryo for a metaclass based api. There's probably a lot of problems with this, so feel free to comment.

```python
# workalendar/core.py
calendars = dict()

class CalendarMeta(type):
    def __new__(cls, name, bases, attrs):
        calendar_type = super(CalendarMeta, cls).__new__(cls, name, bases, attrs)

        if 'isocode' in attrs:
            calendars[attrs['isocode']] = calendar_type

        return calendar_type


class Calendar(object):
    __metaclass__ = CalendarMeta

    FIXED_HOLIDAYS = ()
# …
```

```python
# workalendar/europe.py
# …
class France(WesternCalendar, ChristianMixin):
    "France"
    isocode = 'FRA'
# …
```

Of course, manually populating a dictionary would give the same result.

**Comment by nandoflorestan** [comment]
I would not use a metaclass where a simple dict would suffice. Everyone knows how to add an item to a global dictionary, but not every Python programmer understands metaclasses.

Further, to conserve RAM, I would store in the dictionary not types but strings -- resource specifications such as "some.module:SomeCalendarClass".  Then the system would import only the required module, instead of all calendar modules.  Don't force on me all the calendars of the world if I am only interested in a couple.

**Comment by brunobord** [comment]
> Further, to conserve RAM, I would store in the dictionary not types but strings

good idea. but I don't see how it would work, since you'd have to import the "continent / country" modules in order to build your dict.
I'd rather go for a "on demand" loading of these information. The whole dataaset doesn't have to be loaded by default, or requiring an auto-register mechanism.

**Comment by nandoflorestan** [comment]
It was never a good idea to put each continent in a Python module.  I would put each country in a Python module to start with. If I just want the Sao Paulo calendar, it uses the Brazil calendar as a base anyway.  So fix the bug where it is: in the organization of modules.

Then we provide a separate module containing the mapping and people have the OPTION of using it.

**Comment by thibault** [comment]
@brunobord Do we really have to dynamically build the dict? It could be manually maintained in a static file, and updated every time a new calendar is added. Granted, it makes maintenance a little bit cumbersome.

**Comment by nandoflorestan** [comment]
The resolve() function of my "bag" library takes the aforementioned resource spec and returns the variable it points to: https://github.com/nandoflorestan/bag/blob/master/bag/__init__.py#L25

**Comment by brunobord** [comment]
I see what you mean, bu I really dislike the ":" notation.

> Namespaces are one honking great idea -- let's do more of those!

**Comment by nandoflorestan** [comment]
I see you really dislike the ":" notation, but not what you mean.

(I *think* it simplifies the implementation, separating modules from variables.)

**Comment by nedlowe** [comment]
Hi,

Is this still on the roadmap?  For now, I've worked around it with a lame mapping from ISO 3166 (alpha-3) to the relevant holiday class - but I'd love to be able to delete my mapping...

Many thanks,
Ned
