### ISSUE TITLE
Possibility to install a subset of countries

### ISSUE THREAD

**Issue by canassa** [peopledoc/workalendar#312]
Hello,

First of all, thank you for creating this amazing library! 👍 

This is not an issue, it's just an idea/feature request. We are deploying our Python applications in AWS lambdas, lambdas are all well and good but they have their limitations as well, and one them is the total package size which is limited to 50 MB limit. We tried to use Workalendar as one of our dependencies but it, unfortunately, blew up our 50 MB limit. There are ways to work around it, we are aware of that, but those workarounds also involve an increase in the lambda cold start time.

Our use case is very simple: we just need to know the working days here in The Netherlands. Therefore we "fixed" our issue by just extracting the Dutch working days into a vendor library. But I was wondering that this must be a very common use case for other people as well, I mean, I believe that most people just need to know the working days of their own country or maybe a few extra ones. Therefore, most of the code (and dependencies like ephem and lunardate) being installed is just not being used at all. I think that #302 is related to this

I think that this could be solved by splitting this library into several, one core library plus several extra ones for each country. The installation could be done by using the Setuptools `extra_requires`, e.g.:

```python
setup(
    name="workalendar",
    ...
    extras_require={
        'netherlands':  ["workalendar-netherlands"],
        'germany':  ["workalendar-germany"],
        'europe':  ["workalendar-netherlands", "workalendar-germany", ...],
        ...
        'islamic':  [...],
        'all':  [...],
    }
)
```

One drawback of this approach is that the virtualenv might get convoluted for people that require many countries. This might be a problem because many people are doing `pip freeze > requirements.txt`. One way to work around this would be to write some scripts that automatically vendorize the dependencies and publish pre-built packages to PyPI. Anyway, I understand that this is a huge change to the project, so I think it is probably unfeasible?

Thanks!

**Comment by brunobord** [comment]
> I understand that this is a huge change to the project, so I think it is probably unfeasible?

You're probably right here: it's a huge huge huge change.

As an illustration, right now, there are 174 calendars registered in the ISO registry, and there are a lot of calendars that are not registered in it (Scotland regions, FranceAlsaceMoselle, etc). And a lot of countries are missing in this library, even if we are improving it on a regular basis.

Now... if I wanted to do what you're suggesting, this would mean to create **at least 174 individual  Python packages**. And maintain them in a vast organization, and put up test suites for all of them, individually **and** when they're combined.
Let's imagine we're fixing a bug in the "workalendar core" library, it would require to test **every single calendar** from our catalog in their own dedicated test suite. The more you have independant pieces that are related to each other, the more likely you'll have one of them that would fail, and while you're fixing the problem here, you're triggering another somewhere else.

And then in the ``extra_requires`` dictionary in our ``setup.py`` script, we would have to maintain a list of all the countries, one by one, and then the list of all the countries that belong to Europe, all the Asians, Americans, etc.

You're also suggesting to have an "islamic" "extra". Did you know that some countries are using both Islamic and Christian calendar? (Angola and Benin, for example). Where should we add them? both in "islamic" and "christian"?

Where would we stop the number of subdivisions?

I guess that the number of combinations would grow exponentially... and then the complexity of the setup.py and then... it's too much error prone.

And I'm not mentionning the fact that external contributors, and they're sometimes beginners in Python, would have to manually add their new countries to the various lists in this setup file. Sometimes it's even hard to have flake8-ready code, so I don't think it'd be a good idea to add this burden for contributors.

I'm going to close this issue, feel free to reopen it if you can find an alternative solution, but as far as I'm concerned, I don't think we can switch to this "individual calendar mode".
