### ISSUE TITLE
License conflicts

### ISSUE THREAD

**Issue by muratabur** [peopledoc/workalendar#346]
Hello, 

This project is licensed as MIT, however it has dependencies which potentially conflict with this. In particular, `lunardate` and `pyCalverter`are GPL which I believe would require `workalendar` to have a GPL license as well. 

eg.
https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l

**Comment by brunobord** [comment]
Hello,

First of all, thank you for your input, it raises very interesting questions about this project.

**Disclaimer:** *I'm not a lawyer, obviously, but I think I have a small grasp on licensing.*

I've always considered the GPL as "code-based" ; it's obvious for me that if in your project you're "borrowing" (copy & paste) portions of code from a GPL-licensed codebase, **and** if you're redistributing this resulting work, then you **have** to license it alike, using the GPL or derivative. That's the result of the four freedoms of Free Software: Use the software, Study the software, Make changes to the software, Redistribute verbatim or altered version of the software.

The stackoverflow question you're pointing at is speaking about *linking* and that's in my opinion the key point here.

"Linking" looks like the "C++" or compiled language related sort of links. In that case, the library code is embedded in the resulting piece of software you're redistributing (the binary). And in that case, I agree that the virality of the GPL would apply.

Although there's a gray zone when it comes to the dynamically linked libraries you need to run the software. Of course, `workalendar` requires `lunardate` or `pyCalverter` to compute some calendars, but we are not *redistributing*  their source code along within the PyPI package.

And, as far as I can tell, there's no GPL code in `workalendar` code.

There's [an interesting answer](https://opensource.stackexchange.com/a/4557) in the stackoverflow page you were pointing at:

> **Yes, I can use the MIT license. This is my own code and I can use any license I please.** (I assume I am not copying any GPL-licensed code in my MIT-licensed library). Furthermore, the MIT license is considered by the Free Software Foundation [as compatible](https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean) with [the GPL](https://www.gnu.org/licenses/license-list.en.html#Expat) and LGPL licenses (all versions). There are plenty of examples of MIT-licensed code used in combination of GPL-licensed code, for instance in the [Linux Kernel](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/gpu/drm/drm_agpsupport.c?id=refs/tags/v4.8-rc8)

It conforts me in the opinion that I can write MIT-licensed software that would use GPL-licensed software dynamically, as long as my code doesn't include GPL-licensed material.

The GNU.org FAQ article is not clear, though: I don't know if it's really about "using a MIT-license code in a GPL software" or "using GPL-licensed software within a MIT-license code".

Again, <abbr title="I Am Not A Lawyer">IANAL</abbr>, and we may find a wide range of arguments againts this point of view.

So now, what are the alternative?

### 1 - Change the license towards GPL.

That would be annoying for some reasons:

* We would have to ask permission to our company technical executives. I don't know if it would be a problem, but you're never sure.
* We would have to contact [**every contributor** of the project](https://github.com/peopledoc/workalendar/graphs/contributors) (44 as we're speaking) and ask them for permission to relicense their code. And if any of them is refusing (or not responding...), this would go nowhere. I don't want to blame some people, but I've witnessed that github contributors may sometimes be very unresponsive, even to questions on their freshly-baked PR, so what about a patch they did two or three years ago? :/
* This library is meant to be used as freely as possible. When we started it, it was to be integrated into our proprietary software. I don't know how a license change would prevent some of our users to stop integrating workalendar in their own piece of software, because of the GPL virality, that may scare some CTOs. In that regard, the MIT license seems more suited for a *library*

### 2 - Dual-license GPL+MIT

This "more flexible way" to license this software may look more appealing... But again, it would require us to ask for permission to our hierarchy and contributors. With the same issues if we've got no response or a negative one.

### 3 - Drop "viral" dependencies

Could be a lot more difficult: that would mean to completely replace those libraries by non-viral libraries, if they exist. And if they do not, write our own. I'm not sure I want to compute the phases of the moon myself, it goes beyond my field of expertise.

### 4 - Status quo

So far, having this project licensed under the terms of the MIT License means that anybody can use `workalendar` for their own needs: whether you're building a proprietary or Free software, using verbatim or modified code does not require you to enforce the virality of the license, but encourages you to do so if you want it.

The license as it is would not be seen as a barrier, but as an incentive to contribue.

And I like it this way.

I'm going to close this issue, but the door is not definitely closed and we may try to find another way out in the future.

Hope you'll still be a happy user and maybe one day a contributor ; and if you don't want to, that's fine, no offense taken :o)

Bruno Bord.

**Comment by pennersr** [comment]
For some projects leaving licensing issues like these open for interpretation and debate is simply not an option. If you want absolute certainty, `lunardate` and `pyCalverter` need to be addressed.

For that purpose, I have forked this repo over to https://gitlab.com/pennersr/workalendar/tree/license-conflict/workalendar and removed both of these dependencies. For my purposes, stubbing these is sufficient as I am only interested in European date handling.

**Comment by Natim** [comment]
I would be in favor of dropping GPL dependencies or asking for them to move to LGPL.

**Comment by pennersr** [comment]
@brunobord IMHO this issue should be reopened, and the least you should do is add a warning/notice to the licensing section of the `README.rst`.

**Comment by ewjoachim** [comment]
Maybe another solution could be to add them as an "extra_requires" named "gpl_licensed", so that people could still `pip install workalendar[gpl_licensed]`

**Comment by brunobord** [comment]
@ewjoachim but that would probably break the library and its auto-loaded registry (on an import failure, what happens?)

**Comment by adibo** [comment]
Dear all, thank you for great work and this valuable discussion! 
I'm also considering using `workalendar` but have no need for any of GPL-licensed modules it currently seems to provide (always).

Reading through this thread it seems to me that using "extras_require" could be an acceptable solution as long as the **default installation would behave as it used to**. 

So, maybe one way around this issue would be to have default install (`pip install workalendar`) behave as currently (i.e. installing all dependencies) and use "extras_require" (`pip install workalendar[minimal]` or `pip install workalendar[no-gpl]`) to disable installing unwanted libraries? 

I did some digging in this direction and it seems that this is not yet possible with `setuptools`. However, the case of default "extras_require" (which I suppose would help in this particular case) is under discussion. Here is the reference to keep track of: https://github.com/pypa/setuptools/issues/1139

Or are there alternatives I'm missing?
