### ISSUE TITLE
Japan missing some holidays

### ISSUE THREAD

**Issue by raybuhr** [peopledoc/workalendar#369]
Specifically, I was trying to use this package to check when banks are open. It worked pretty well, except Japan seems to have more holidays that aren't included here, such as Jan 2 and Jan 3 being New Year Bank Holidays.

Resources:
https://www.timeanddate.com/holidays/japan/
https://www.boj.or.jp/en/about/outline/holi.htm/

**Comment by brunobord** [comment]
I understand your issue here. As far as I can say, the Japan calendar doesn't include bank holidays because they're only observed by banks (and maybe other institutions, but I don't know precisely).

It's been discussed in other channels, but in the future more "institutional" calendars might be added to the library, as it is already the case in some modules. Here are a few examples:

* the [California Education calendar](https://github.com/peopledoc/workalendar/blob/master/workalendar/usa/california.py#L18-L38).
* the [Central European Bank calendar](https://github.com/peopledoc/workalendar/blob/master/workalendar/europe/european_central_bank.py).

Now what can we do today? I guess that it's doable to build a `JapanBank` calendar that would inherit from the `Japan` class, and adjust it with the corresponding bank holidays. If you think you can propose a Pull Request, please don't hesitate, I'd be glad to review it!
That'd be a very valuable contribution!

**Comment by raybuhr** [comment]
Thanks for the feedback and suggestion. I'll try taking a stab at a PR for `JapanBank` calendar sometime this week (probably Friday).

**Comment by brunobord** [comment]
@raybuhr woot!!! :o)

**Comment by raybuhr** [comment]
Took me longer to get to this than I would have liked, but I pushed up a draft PR #379 that I think accomplishes all the logic to create the `JapanBank` calendar, as well as fix some issues with the `Japan` calendar due to the changing of the emperor this year -- though it might be more accurate to move some of the holidays from `JapanBank` to `Japan`. I still need to add the test cases and update the changelog and readme.

**Comment by brunobord** [comment]
I'm happy to announce that your patch for Japan calendars are available for download on the v5.2.0 version that has just been released: https://pypi.org/project/workalendar/5.2.0/
