### ISSUE TITLE
Flag original dates for observed days 

### ISSUE THREAD

**Issue by jbroudou** [peopledoc/workalendar#490]
When an observed day (i.e. holidays that are moved because they are on a weekend) is returned would it possible to flag what the original date was rather than relying on a string suffix? 

Also, in some locations when a holiday falls on a weekend, it is moved to a weekday as an observed day. In some of these locations only the observed day is considered a holiday whereas in others both the observed and original days are considered holidays. This is an important distinction in some jurisdictions. 

Is there any chance of supporting an additional flag against observed holidays that indicate the original day is or isn't a holiday?

**Comment by brunobord** [comment]
Your suggestion would change a lot of things in the API of workalendar, if I understand correctly your point.

So far, the `holidays()` method in workalendar only returns a tuple, composed by a date and a string. I'm really attached to this elementary data structure, because there's no extra data surrounding it. You want a calendar, you have dates and a label. KISS principle.

If we had to return these calendars with an extra flag meaning that it's a "true" holiday or not, this would mean it'd break the API for **every** workalendar user. Because:

1. we can't define an extra property to a tuple. Or we would have to define a class that inherits from a tuple, and it's generally a bad idea to try to override a built-in type,
2. or we may define a core class, `Holiday`, with core properties such as the date & label, but with extra properties.

But doing either 1. or 2, would mean to change **every single calendar** and the way they build their holiday list. And also, every 3rd party application using `workalendar` would have to rewrite the way they're accessing the holidays... That'd represent a lot of workload, caused by a feature you might not be interested in.

Now onto your use-case:

I think that if this kind of distinction between a holiday and a non-holiday should be treated case by case in each calendar that makes this distinction.

If for example *May 1st* is a non-working day and it's not counted as a holiday if it falls on Sundays, then your ̀`holidays()` method shouldn't return it in the list. If both the regular day and the observed day are counted as holidays, then make it so by returning both of them in the holiday list. I think it's doable for the precise jurisdictions that demand it ; and I'd be glad to review and integrate these patches to improve the `workalendar` library accuracy in these calendars.

And if by some ways it appears that your special case can't be processed at the `workalendar` calendar class, then you'll have to externalise this by building a wrapper around this holiday list. Iterate over the days and remove those who should be removed, because *you* know how the days must be post-processed, the specifics of it.

What do you think of these alternatives?

**Comment by jbroudou** [comment]
@brunobord  Your suggestion of not returning May 1st if it isn't counted as a holiday (as it falls on a Sunday) doesn't address scenarios where users of Calendars need to see the original dates of a holiday once it has moved. 

Take for example https://www.industrialrelations.nsw.gov.au/public-holidays/public-holidays-in-nsw/

> 2 The public holiday standard in the Public Holidays Act 2010 provides that when Australia Day (26 January) falls on a Saturday or Sunday, there will be no public holiday on that day and instead the following Monday is to be the public holiday.

In any case, I understand that given the current simple structure that is returned this would require significant changes that would break projects downstream.
