### ISSUE TITLE
Doubt on Rosh Hashana Eve in Israel calendar

### ISSUE THREAD

**Issue by brunobord** [peopledoc/workalendar#537]
As you can see on today's code, _Rosh Hashana Eve_ is a holiday in Israel calendar: https://github.com/peopledoc/workalendar/blob/11bd8b0e446f84d0549c6b842cb3ef2d216b3ec0/workalendar/asia/israel.py

```python
holidays_hebrew_dates = [
    (HebrewDate(jewish_year, 6, 29), "Rosh Hashana Eve"),
    (HebrewDate(jewish_year + 1, 7, 1), "Rosh Hashana"),
    (HebrewDate(jewish_year + 1, 7, 2), "Rosh Hashana"),
    (HebrewDate(jewish_year + 1, 7, 9), "Yom Kippur Eve"),
    # ....
]
```

But after reading Wikipedia's article, I'm not sure... https://en.wikipedia.org/wiki/Public_holidays_in_Israel

It says there that it's only the 2 Rosh Hashana days that are non-working days, but not the day before.

I'm paging @elaav, @armona and @orzarchi, who have worked on this calendar, to investigate if this is a bug or not, and if needed, how to fix it.

**Comment by armona** [comment]
Rosh HaShana eve is considered a "half day" holiday in the Jewish community. 
A lot of people take the entire day as holiday.

**Comment by ewjoachim** [comment]
Thanks for your answer, but I'm reading what you're saying the other way around: this lib tracks legal holidays.
In your first sentence, your talking about the Jewish community, we're interested in the country law.
In your second answer, I understand "A lot of people take the day" as "this is a choice people make", and workalendar is about legal holidays.

So what I understand from your answer is that it isn't a legal holiday. Am I understanding this wrong?

Note: We could have a second calendar tracking Jewish-observant holidays because I'm guessing a lot of businesses will follow those even if it's not required by the (country) law (vs religious law).

On the other hand, it looks like e.g. post offices are closed on holiday eve afternoons. I'm not sure how we would even implement a half holiday...

**Comment by RomanIvn** [comment]
In Israel, every employee can decide which religion holidays he want to receive. Most people and businesses will go with the Jewish holidays, Muslims and Christians can decide to follow their traditional days. Employees in the same organization can be at holiday on separate days.
In Jewish tradition there is  "Erev Hag" which is the night that the holiday first arrives. Usually, these days are shorter days like a Friday (150%).  
The day after "Erev Hag" is the holiday itself and is like a Saturday (200%).
Sometimes holidays can have an "Erev hag" at their beginning and another "Erev hag" at the end (When its a multiple days long holiday).
https://www.kolzchut.org.il/he/חגים_יהודיים

https://translate.google.com/translate?hl=&sl=iw&tl=en&u=https%3A%2F%2Fwww.kolzchut.org.il%2Fhe%2F%D7%97%D7%92%D7%99%D7%9D_%D7%99%D7%94%D7%95%D7%93%D7%99%D7%99%D7%9D

**Comment by orzarchi** [comment]
I would keep the current code as is.
Take for example the national holidays observed by the israeli stock market (a major reason for using a library like this):
https://info.tase.co.il/Eng/about_tase/corporate/Pages/2021.aspx
You can see that Rosh Hashana Eve (Jewish new year) is a no trading day.

**Comment by brunobord** [comment]
ok, so be it.
thank you everyone for your input.
