### ISSUE TITLE
Catalonia without ISO code

### ISSUE THREAD

**Issue by jbagot** [peopledoc/workalendar#551]
Hi,

I saw that Catalonia is the only class without a @iso_register decorator in the class. Then the only way that I found to use it is using the `register` method to register this region.
Why doesn't have this decorator?

Am I missing something?

Thanks

**Comment by brunobord** [comment]
Hello,

Don't worry, you're not missing anything. Catalonia doesn't have a decorator probably because at the time we made this calendar, and at the time we built the ISO registry, assigning ISO codes to sub-regions was not on the table.
And after that, this calendar was forgotten when we could assign it.

And you're right, it should have one.
We may link this issue to the upcoming https://github.com/peopledoc/workalendar/issues/531 issue, in which I've already planned to add ISO codes for all Spain provinces.

If you wish, in the meantime, you could also make a PR to add the ISO code and associated tests, because I'm not sure of when I'll be able to work on the Spain sub-regions.

If you need some help, do not hesitate to ask!

**Comment by brunobord** [comment]
PR merged, I'm about to make a release that includes this change.

**Comment by brunobord** [comment]
Release v11.0.1 was published on PyPI ; happy upgrading!

* https://github.com/peopledoc/workalendar/releases/tag/11.0.1
* https://pypi.org/project/workalendar/11.0.1/
